package com.example.myapplication3.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myapplication3.data.DisBase;

import com.example.myapplication3.greendao.DisBaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig disBaseDaoConfig;

    private final DisBaseDao disBaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        disBaseDaoConfig = daoConfigMap.get(DisBaseDao.class).clone();
        disBaseDaoConfig.initIdentityScope(type);

        disBaseDao = new DisBaseDao(disBaseDaoConfig, this);

        registerDao(DisBase.class, disBaseDao);
    }
    
    public void clear() {
        disBaseDaoConfig.clearIdentityScope();
    }

    public DisBaseDao getDisBaseDao() {
        return disBaseDao;
    }

}
