package com.example.myapplication3.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.myapplication3.data.MyCode;

import com.example.myapplication3.greendao.MyCodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCodeDaoConfig;

    private final MyCodeDao myCodeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCodeDaoConfig = daoConfigMap.get(MyCodeDao.class).clone();
        myCodeDaoConfig.initIdentityScope(type);

        myCodeDao = new MyCodeDao(myCodeDaoConfig, this);

        registerDao(MyCode.class, myCodeDao);
    }
    
    public void clear() {
        myCodeDaoConfig.clearIdentityScope();
    }

    public MyCodeDao getMyCodeDao() {
        return myCodeDao;
    }

}
